**1) Write a Python program which accepts a list named :randomList = ['a',0,2]. Use exception handling using try-catch which gives the output as:**

Output:

1) If the List element is a alphabet or string, the output will be 

The entry is a 

Oops! <class 'ValueError'>occured. Next entry.

2) If the List element is "0", the output will be 

The entry is 0

Oops! <class 'ZeroDivisionError'>occured. Next entry.

3) If the List element is and integer except 0, then output will be 

The entry is 2

The reciprocal of 2 is 0.5 // reciprocal of an integer

In [1]:
def reciprocalFunc(randomList):
    length = len(randomList) -1 
    for index, item in enumerate(randomList):  
        try:
            print("The entry is "+str(item))
            value = 1/int(item)
            print("The reciprocal of {} is {} // reciprocal of an integer".format(item, str(value)),end='')            
        except ValueError:
            print("Oops! <class 'ValueError'> occured. ",end='')            
        except ZeroDivisionError:
            print("Oops! <class 'ZeroDivisionError'> occured. ",end='')
        if(index != length):
            print("Next entry.")

randomList = ['a',0,2]
reciprocalFunc(randomList)

The entry is a
Oops! <class 'ValueError'> occured. Next entry.
The entry is 0
Oops! <class 'ZeroDivisionError'> occured. Next entry.
The entry is 2
The reciprocal of 2 is 0.5 // reciprocal of an integer

**2) Array out of Bound Exception**

Write a Python program to give exception "Array Out of Bound" if the user wants to access the elements beyond the list size (use try and except)

In [2]:
def accessList(index):
    myList=[10,20,30,40,50,60]
    try:
        print("The element present at the position of {} is : {}. ".format(index, myList[index]))
    except IndexError as IE:
        print("You are trying to access an element which is beyond the list size. Please enter a number between 0-6. Reason:"+str(IE))
        
a = int(input("Enter a number to access an element from a list in that position."))
accessList(a)

Enter a number to access an element from a list in that position.7
You are trying to access an element which is beyond the list size. Please enter a number between 0-6. Reason:list index out of range

**3) Write a Python module script that contains fib2() method to calculate the Fibonacci series till 1000 and save it as fibo.py.**


Note: The module created as fibo.py has to be placed in lib folder:

For linux/ubuntu path = /home/anaconda/lib/python2

For Windows path = C:\Users\Acadgild\Anaconda3\Lib

In [4]:
import fibo as fb

n = int(input("Enter a number to generate fibonacci series."))
fb.fibo2(n)

Enter a number to generate fibonacci series.17
0
1
1
2
3
5
8
13
21
34
55
89
144
233
377
610
987

**4) Write a python module script that contains ispalindrome() method to calculate the input string as palindrome string or not and save it as palindrome.py**

In [7]:
import palindrome as plnd

plnd.isPalindrome('Malayalam')

malayalam is palindrome

**5) Write a program in Python with one class called Cipher. Within the constructor of this class, ask user for a string and store it. Use a static variable, key to store a randomly generated integer between 1 and 50 inclusive. Implement two methods, encrypt and decrypt within this class. Encrypt generates and print a cipher text using the user-entered string and the key and encrypt generates decrypted string from ciphertext. The cipher only encrypts alpha and numeric (A-Z, a-z, 0-9). All Symbols, such as -,;%, remain unencrypted. The cipher text can have special characters. Use generator expression to filter out alpha and numeric characters of the input string and to generate cipher text. Create an instance of this class, encrypt and decrypt back the user entered string.**

In [34]:
import numpy.random as rnd
import re

key = "s3cr3tkeys"

class Cipher:    
        
    def __init__(self,text):
        self.text = text
        print("Entered text "+self.text)
        plaintext = ''.join(ch for ch in self.text if ch.isalnum()) 
        print("Plain text: "+plaintext)
        ciphertext = self.encrypt(plaintext)
        print("Encrypted String: "+str(ciphertext))
        plaintext = self.decrypt(ciphertext)
        print("Decrypted String: "+plaintext)
    
    def encrypt(self, clear_text):
        return "".join([chr(ord(c1) ^ ord(c2)) for (c1,c2) in zip(clear_text,key)])
                        
    
    def decrypt(self,cipher_text):
        return "".join([chr(ord(c1) ^ ord(c2)) for (c1,c2) in zip(cipher_text,key)])
        
         
text = input("Enter a string")
obj = Cipher(text)

Enter a stringH3llo-W0rld
Entered text H3llo-W0rld
Plain text: H3lloW0rld
Encrypted String: ; \#[
Decrypted String: H3lloW0rld

**6) Get Data from the following link:**

http://files.grouplens.org/datasets/movielens/ml-20m.zip

We will be using the following files for this exercise:

ratings.csv: userId,movieId,rating,timestamp

tags.csv: userId, movieId, tag, timestamp

movies.csv: moviesId, title, genres


**I. Read the dataset using pandas.**

In [2]:
import pandas as pd
import os

os.chdir(r"F:\Data Science Master\Assignments\ml-20m\ml-20m")
df_tags = pd.read_csv("tags.csv")
df_movies = pd.read_csv("movies.csv")
df_ratings = pd.read_csv("ratings.csv")

print("Reading dataset from tags.csv")
df_tags.head()

Reading dataset from tags.csv

   userId  movieId            tag   timestamp
0      18     4141    Mark Waters  1240597180
1      65      208      dark hero  1368150078
2      65      353      dark hero  1368150079
3      65      521  noir thriller  1368149983
4      65      592      dark hero  1368150078

**II. Extract the first row from tags and print its type.**

In [13]:
df_tags.iloc[0]

userId                18
movieId             4141
tag          Mark Waters
timestamp     1240597180
Name: 0, dtype: object

**III. Extract row 0,11,2000 from tags DataFrame.**

In [17]:
df_tags.iloc[[0,11,2000]]

      userId  movieId                tag   timestamp
0         18     4141        Mark Waters  1240597180
11        65     1783      noir thriller  1368149983
2000     910    68554  conspiracy theory  1368043943

**IV. Print index, columns of the DataFrame.**

In [23]:
print(df_tags.index)
print(df_tags.columns)

RangeIndex(start=0, stop=465564, step=1)
Index(['userId', 'movieId', 'tag', 'timestamp'], dtype='object')

**V. Calculate descriptive statistics for the 'ratings' column of the ratings DataFrame. Verify using describe().**

In [29]:
df_ratings.describe()

             userId       movieId        rating     timestamp
count  1.048575e+06  1.048575e+06  1.048575e+06  1.048575e+06
mean   3.527086e+03  8.648988e+03  3.529272e+00  1.096036e+09
std    2.018424e+03  1.910014e+04  1.051919e+00  1.594899e+08
min    1.000000e+00  1.000000e+00  5.000000e-01  8.254999e+08
25%    1.813000e+03  9.030000e+02  3.000000e+00  9.658382e+08
50%    3.540000e+03  2.143000e+03  4.000000e+00  1.099263e+09
75%    5.233000e+03  4.641000e+03  4.000000e+00  1.217407e+09
max    7.120000e+03  1.306420e+05  5.000000e+00  1.427764e+09

**VI. Filter out ratings with rating > 5**

In [33]:
df_ratings[df_ratings['rating'] > 5]
#Maximum rating is found to be 5. Hence no record is displayed. It will show records with the values less than 5.

Empty DataFrame
Columns: [userId, movieId, rating, timestamp]
Index: []

**VII. Find how many null values, missing values are present. Deal with them. Print out how many rows have been modified.**

In [57]:
missing_info = list(df_movies.columns[df_movies.isnull().any()])
for col in missing_info:
    num_missing = df_movies[df_movies[col].isnull() == True].shape[0]
    print('number missing for column {}: {}'.format(col, num_missing))

number missing for column Year: 17

**VIII. Filter out movies from the movies DataFrame that are of type 'Animation'.**

In [25]:
df_movies[df_movies['genres'].str.contains("Animation")]

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
12,13,Balto (1995),Adventure|Animation|Children
47,48,Pocahontas (1995),Animation|Children|Drama|Musical|Romance
236,239,"Goofy Movie, A (1995)",Animation|Children|Comedy|Romance
241,244,Gumby: The Movie (1995),Animation|Children
310,313,"Swan Princess, The (1994)",Animation|Children
360,364,"Lion King, The (1994)",Adventure|Animation|Children|Drama|Musical|IMAX
388,392,"Secret Adventures of Tom Thumb, The (1993)",Adventure|Animation
547,551,"Nightmare Before Christmas, The (1993)",Animation|Children|Fantasy|Musical
553,558,"Pagemaster, The (1994)",Action|Adventure|Animation|Children|Fantasy
582,588,Aladdin (1992),Adventure|Animation|Children|Comedy|Musical
588,594,Snow White and the Seven Dwarfs (1937),Animation|Children|Drama|Fantasy|Musical
589,595,Beauty and the Beast (1991),Animation|Children|Fantasy|Musical|Romance|IMAX
590,596,Pinocchio (1940),Animation|Children|Fantasy|Musical
604,610,Heavy Metal (1981),Action|Adventure|Animation|Horror|Sci-Fi
610,616,"Aristocats, The (1970)",Animation|Children
624,631,All Dogs Go to Heaven 2 (1996),Adventure|Animation|Children|Fantasy|Musical|R...
653,661,James and the Giant Peach (1996),Adventure|Animation|Children|Fantasy|Musical
664,673,Space Jam (1996),Adventure|Animation|Children|Comedy|Fantasy|Sc...
697,709,Oliver & Company (1988),Adventure|Animation|Children|Comedy|Musical
708,720,Wallace & Gromit: The Best of Aardman Animatio...,Adventure|Animation|Comedy
728,741,Ghost in the Shell (Kôkaku kidôtai) (1995),Animation|Sci-Fi
732,745,Wallace & Gromit: A Close Shave (1995),Animation|Children|Comedy
770,783,"Hunchback of Notre Dame, The (1996)",Animation|Children|Drama|Musical|Romance
871,888,Land Before Time III: The Time of the Great Gi...,Adventure|Animation|Children|Musical
1003,1022,Cinderella (1950),Animation|Children|Fantasy|Musical|Romance
1004,1023,Winnie the Pooh and the Blustery Day (1968),Animation|Children|Musical
1005,1024,"Three Caballeros, The (1945)",Animation|Children|Musical
1006,1025,"Sword in the Stone, The (1963)",Animation|Children|Fantasy|Musical
1010,1029,Dumbo (1941),Animation|Children|Drama|Musical
...,...,...,...
27007,129830,Animals United (2011),Animation|Children|Comedy
27008,129834,Tom and Jerry: The Lost Dragon (2014),Animation|Children|Comedy
27018,129859,Mardock Scramble: The Second Combustion (2011),Animation|Sci-Fi
27054,130034,Stand by Me Doraemon (2014),Animation|Children|Drama|Fantasy
27070,130075,Frozen Fever (2015),Adventure|Animation
27103,130394,The Mascot (1934),Animation
27107,130402,Cardcaptor Sakura: The Sealed Card (2000),Adventure|Animation|Comedy|Fantasy|Romance
27129,130506,Berserk: The Golden Age Arc 2 - The Battle for...,Action|Animation|Fantasy
27130,130508,Berserk: The Golden Age Arc - The Egg of the K...,Action|Adventure|Animation|Fantasy|Horror
27131,130510,Berserk: The Golden Age Arc 3 - Descent (2013),Action|Animation|Fantasy
27135,130518,The Amazing Screw-On Head (2006),Action|Adventure|Animation|Comedy|Sci-Fi
27136,130520,Home (2015),Animation|Children|Comedy|Fantasy|Sci-Fi
27137,130522,The Brave Little Toaster Goes to Mars (1998),Animation|Children
27155,130644,The Garden of Sinners - Chapter 5: Paradox Par...,Animation
27205,131058,Santa's Apprentice (2010),Animation|Children
27208,131066,Ronal the Barbarian (2011),Adventure|Animation|Fantasy
27215,131080,Cinderella III: A Twist in Time (2007),Animation|Children|Fantasy|Romance
27218,131086,The Little Polar Bear: Lars and the Little Tig...,Animation|Children
27221,131092,"Mickey, Donald, Goofy: The Three Musketeers (2...",Adventure|Animation|Children|Comedy
27222,131094,Rudolph the Red-Nosed Reindeer: The Movie (1998),Animation|Children
27224,131098,Saving Santa (2013),Animation|Children|Comedy
27226,131102,Lucky Luke: The Ballad of the Daltons (1978),Animation|Children|Comedy|Western
27228,131106,Casper's Haunted Christmas (2000),Animation|Children
27235,131120,Superstar Goofy (1991),Animation|Children|Comedy
27240,131130,Tom and Jerry: A Nutcracker Tale (2007),Animation|Comedy
27241,131132,Kleines Arschloch - Der Film (1997),Animation|Comedy
27247,131144,Werner - Das muss kesseln!!! (1996),Animation|Comedy
27248,131146,Werner - Volles Rooäää (1999),Animation|Comedy
27269,131243,Werner - Gekotzt wird später (2003),Animation|Comedy
27270,131248,Brother Bear 2 (2006),Adventure|Animation|Children|Comedy|Fantasy

**IX. Find the average rating of movies.**

In [35]:
df = pd.DataFrame(df_ratings, columns=['movieId', 'rating'])
#only printing first five average rating.
df.groupby('movieId').mean().reset_index().head()

   movieId    rating
0        1  3.959323
1        2  3.268398
2        3  3.186861
3        4  3.000000
4        5  3.143836

**X. Perform an inner join of movies and tags based on movieId.**

In [26]:
pd.merge(df_movies, df_tags, on='movieId', how='inner')

,movieId,title,genres,userId,tag,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1644,Watched,1417736680
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1741,computer animation,1183903155
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1741,Disney animated feature,1183933307
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1741,Pixar animation,1183934770
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1741,TÃ©a Leoni does not star in this movie,1245093573
5,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,2299,Pixar,1403306852
6,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,3596,animation,1290312028
7,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,3596,family,1290312032
8,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,3596,Tom Hanks,1290312036
9,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,6233,Pixar,1387079572
10,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,6233,witty,1387079576
11,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,8219,Pixar,1159534063
12,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,10616,adventure,1277357423
13,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,10616,animated,1277357419
14,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,10616,animation,1277357417
15,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,10616,clever,1277357438
16,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,10616,comedy,1277357433
17,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,10616,computer animation,1277357405
18,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,10616,family,1277357449
19,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,10616,fantasy,1277357430
20,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,10616,Tom Hanks,1277357411
21,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,11081,bright,1173304070
22,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,11081,DARING RESCUES,1173304095
23,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,11081,fanciful,1173304058
24,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,11081,HEROIC MISSION,1173304102
25,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,11081,humorous,1173304049
26,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,11081,light,1173304062
27,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,11081,rousing,1173304074
28,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,11081,TOYS COME TO LIFE,1173304091
29,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,11081,UNLIKELY FRIENDSHIPS,1173304106
...,...,...,...,...,...,...
465534,131015,Hellgate (2011),Horror|Thriller,25978,Cary Elwes,1427585540
465535,131015,Hellgate (2011),Horror|Thriller,25978,Demons,1427585566
465536,131015,Hellgate (2011),Horror|Thriller,25978,Exorcism,1427585551
465537,131015,Hellgate (2011),Horror|Thriller,25978,Ghosts,1427585546
465538,131015,Hellgate (2011),Horror|Thriller,25978,Monks,1427585560
465539,131015,Hellgate (2011),Horror|Thriller,25978,nurse,1427585621
465540,131015,Hellgate (2011),Horror|Thriller,25978,psychic,1427585613
465541,131015,Hellgate (2011),Horror|Thriller,25978,slow,1427585575
465542,131015,Hellgate (2011),Horror|Thriller,25978,special effects,1427585690
465543,131015,Hellgate (2011),Horror|Thriller,25978,surfing,1427585592
465544,131015,Hellgate (2011),Horror|Thriller,25978,Thailand,1427585543
465545,131015,Hellgate (2011),Horror|Thriller,25978,William Hurt,1427585696
465546,131031,La liga no es cosa de hombres (1972),(no genres listed),33323,Barcelona,1427641562
465547,131031,La liga no es cosa de hombres (1972),(no genres listed),33323,exploitation,1427641559
465548,131031,La liga no es cosa de hombres (1972),(no genres listed),33323,female football,1427641577
465549,131031,La liga no es cosa de hombres (1972),(no genres listed),33323,football,1427641548
465550,131031,La liga no es cosa de hombres (1972),(no genres listed),33323,Rome,1427641564
465551,131031,La liga no es cosa de hombres (1972),(no genres listed),33323,shorts,1427641571
465552,131031,La liga no es cosa de hombres (1972),(no genres listed),33323,soccer,1427641556
465553,131031,La liga no es cosa de hombres (1972),(no genres listed),33323,transvestite,1427641589
465554,131054,Dinotopia: Quest for the Ruby Sunstone (2005),Children|Fantasy|Sci-Fi,88144,dinosaurs,1427654430
465555,131082,Playground (2009),(no genres listed),92885,documentary,1427654757
465556,131082,Playground (2009),(no genres listed),92885,Yoshitomo Nara,1427654856
465557,131164,Vietnam in HD (2011),War,54560,Vietnam War,1427667401
465558,131170,Parallels (2015),Sci-Fi,88738,alternate reality,1427732804
465559,131258,The Pirates (2014),Adventure,28906,bandits,1427745421
465560,131258,The Pirates (2014),Adventure,28906,Korea,1427745512
465561,131258,The Pirates (2014),Adventure,28906,mutiny,1427745542
465562,131258,The Pirates (2014),Adventure,28906,pirates,1427745419
465563,131258,The Pirates (2014),Adventure,28906,whale,1427745432

**XI. Print out the 5 movies that belong to the Comedy genre and have rating greater than 4.**

In [21]:
df1 = df_movies[df_movies['genres'].str.contains("Comedy")]
merged_df = pd.merge(df1, df_ratings, on='movieId', how='inner')
merged_df[merged_df['rating'] > 4].head()

,movieId,title,genres,userId,rating,timestamp
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,6,5.0,858275452
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,11,4.5,1230858821
7,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,14,4.5,1225311239
9,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,19,5.0,855176628
14,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,34,5.0,846509445

**XII. Split 'genres' into multiple columns.**

In [28]:
df_movies['genres'].str.split('|', expand=True)

,0,1,2,3,4,5,6,7,8,9
0,Adventure,Animation,Children,Comedy,Fantasy,None,None,None,None,None
1,Adventure,Children,Fantasy,None,None,None,None,None,None,None
2,Comedy,Romance,None,None,None,None,None,None,None,None
3,Comedy,Drama,Romance,None,None,None,None,None,None,None
4,Comedy,None,None,None,None,None,None,None,None,None
5,Action,Crime,Thriller,None,None,None,None,None,None,None
6,Comedy,Romance,None,None,None,None,None,None,None,None
7,Adventure,Children,None,None,None,None,None,None,None,None
8,Action,None,None,None,None,None,None,None,None,None
9,Action,Adventure,Thriller,None,None,None,None,None,None,None
10,Comedy,Drama,Romance,None,None,None,None,None,None,None
11,Comedy,Horror,None,None,None,None,None,None,None,None
12,Adventure,Animation,Children,None,None,None,None,None,None,None
13,Drama,None,None,None,None,None,None,None,None,None
14,Action,Adventure,Romance,None,None,None,None,None,None,None
15,Crime,Drama,None,None,None,None,None,None,None,None
16,Drama,Romance,None,None,None,None,None,None,None,None
17,Comedy,None,None,None,None,None,None,None,None,None
18,Comedy,None,None,None,None,None,None,None,None,None
19,Action,Comedy,Crime,Drama,Thriller,None,None,None,None,None
20,Comedy,Crime,Thriller,None,None,None,None,None,None,None
21,Crime,Drama,Horror,Mystery,Thriller,None,None,None,None,None
22,Action,Crime,Thriller,None,None,None,None,None,None,None
23,Drama,Sci-Fi,None,None,None,None,None,None,None,None
24,Drama,Romance,None,None,None,None,None,None,None,None
25,Drama,None,None,None,None,None,None,None,None,None
26,Children,Drama,None,None,None,None,None,None,None,None
27,Drama,Romance,None,None,None,None,None,None,None,None
28,Adventure,Drama,Fantasy,Mystery,Sci-Fi,None,None,None,None,None
29,Crime,Drama,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...
27248,Animation,Comedy,None,None,None,None,None,None,None,None
27249,Comedy,Romance,None,None,None,None,None,None,None,None
27250,Comedy,None,None,None,None,None,None,None,None,None
27251,Comedy,None,None,None,None,None,None,None,None,None
27252,Comedy,None,None,None,None,None,None,None,None,None
27253,Comedy,None,None,None,None,None,None,None,None,None
27254,Comedy,None,None,None,None,None,None,None,None,None
27255,Drama,None,None,None,None,None,None,None,None,None
27256,Drama,Romance,None,None,None,None,None,None,None,None
27257,War,None,None,None,None,None,None,None,None,None
27258,(no genres listed),None,None,None,None,None,None,None,None,None
27259,Drama,None,None,None,None,None,None,None,None,None
27260,Sci-Fi,None,None,None,None,None,None,None,None,None
27261,(no genres listed),None,None,None,None,None,None,None,None,None
27262,Drama,Romance,Thriller,None,None,None,None,None,None,None
27263,Drama,None,None,None,None,None,None,None,None,None
27264,Action,Horror,Thriller,None,None,None,None,None,None,None
27265,Comedy,Romance,None,None,None,None,None,None,None,None
27266,Comedy,None,None,None,None,None,None,None,None,None
27267,Comedy,Drama,None,None,None,None,None,None,None,None
27268,Comedy,Romance,None,None,None,None,None,None,None,None
27269,Animation,Comedy,None,None,None,None,None,None,None,None
27270,Adventure,Animation,Children,Comedy,Fantasy,None,None,None,None,None
27271,Comedy,None,None,None,None,None,None,None,None,None
27272,Comedy,Horror,None,None,None,None,None,None,None,None
27273,Comedy,None,None,None,None,None,None,None,None,None
27274,Comedy,None,None,None,None,None,None,None,None,None
27275,Adventure,None,None,None,None,None,None,None,None,None
27276,(no genres listed),None,None,None,None,None,None,None,None,None
27277,Adventure,Fantasy,Horror,None,None,None,None,None,None,None

**XIII. Extract year from title e.g. (1995).**

In [44]:
df_movies['Year'] = df_movies['title'].str.extract(r"\((.*?)\)", expand=False)
df_movies

,movieId,title,genres,Year
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1995
1,2,Jumanji (1995),Adventure|Children|Fantasy,1995
2,3,Grumpier Old Men (1995),Comedy|Romance,1995
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,1995
4,5,Father of the Bride Part II (1995),Comedy,1995
5,6,Heat (1995),Action|Crime|Thriller,1995
6,7,Sabrina (1995),Comedy|Romance,1995
7,8,Tom and Huck (1995),Adventure|Children,1995
8,9,Sudden Death (1995),Action,1995
9,10,GoldenEye (1995),Action|Adventure|Thriller,1995
10,11,"American President, The (1995)",Comedy|Drama|Romance,1995
11,12,Dracula: Dead and Loving It (1995),Comedy|Horror,1995
12,13,Balto (1995),Adventure|Animation|Children,1995
13,14,Nixon (1995),Drama,1995
14,15,Cutthroat Island (1995),Action|Adventure|Romance,1995
15,16,Casino (1995),Crime|Drama,1995
16,17,Sense and Sensibility (1995),Drama|Romance,1995
17,18,Four Rooms (1995),Comedy,1995
18,19,Ace Ventura: When Nature Calls (1995),Comedy,1995
19,20,Money Train (1995),Action|Comedy|Crime|Drama|Thriller,1995
20,21,Get Shorty (1995),Comedy|Crime|Thriller,1995
21,22,Copycat (1995),Crime|Drama|Horror|Mystery|Thriller,1995
22,23,Assassins (1995),Action|Crime|Thriller,1995
23,24,Powder (1995),Drama|Sci-Fi,1995
24,25,Leaving Las Vegas (1995),Drama|Romance,1995
25,26,Othello (1995),Drama,1995
26,27,Now and Then (1995),Children|Drama,1995
27,28,Persuasion (1995),Drama|Romance,1995
28,29,"City of Lost Children, The (Cité des enfants p...",Adventure|Drama|Fantasy|Mystery|Sci-Fi,"Cité des enfants perdus, La"
29,30,Shanghai Triad (Yao a yao yao dao waipo qiao) ...,Crime|Drama,Yao a yao yao dao waipo qiao
...,...,...,...,...
27248,131146,Werner - Volles Rooäää (1999),Animation|Comedy,1999
27249,131148,What A Man (2011),Comedy|Romance,2011
27250,131150,7 Dwarves: The Forest Is Not Enough (2006),Comedy,2006
27251,131152,The Fat Spy (1966),Comedy,1966
27252,131154,"Die Bademeister – Weiber, saufen, Leben retten...",Comedy,1999
27253,131156,Ants in the Pants 2 (2002),Comedy,2002
27254,131158,"Manta, Manta (1991)",Comedy,1991
27255,131160,Oscar and the Lady in Pink (2009),Drama,2009
27256,131162,Por un puñado de besos (2014),Drama|Romance,2014
27257,131164,Vietnam in HD (2011),War,2011
27258,131166,WWII IN HD (2009),(no genres listed),2009
27259,131168,Phoenix (2014),Drama,2014
27260,131170,Parallels (2015),Sci-Fi,2015
27261,131172,Closed Curtain (2013),(no genres listed),2013
27262,131174,Gentlemen (2014),Drama|Romance|Thriller,2014
27263,131176,A Second Chance (2014),Drama,2014
27264,131180,Dead Rising: Watchtower (2015),Action|Horror|Thriller,2015
27265,131231,Standby (2014),Comedy|Romance,2014
27266,131237,What Men Talk About (2010),Comedy,2010
27267,131239,Three Quarter Moon (2011),Comedy|Drama,2011
27268,131241,Ants in the Pants (2000),Comedy|Romance,2000
27269,131243,Werner - Gekotzt wird später (2003),Animation|Comedy,2003
27270,131248,Brother Bear 2 (2006),Adventure|Animation|Children|Comedy|Fantasy,2006
27271,131250,No More School (2000),Comedy,2000
27272,131252,Forklift Driver Klaus: The First Day on the Jo...,Comedy|Horror,2001
27273,131254,Kein Bund für's Leben (2007),Comedy,2007
27274,131256,"Feuer, Eis & Dosenbier (2002)",Comedy,2002
27275,131258,The Pirates (2014),Adventure,2014
27276,131260,Rentun Ruusu (2001),(no genres listed),2001
27277,131262,Innocence (2014),Adventure|Fantasy|Horror,2014

**XIV. Select rows based on timestamps later than 2015-02-01.**

In [50]:

import time
import datetime
s = "01/02/2015"
mask = ( df_ratings['timestamp'] > time.mktime(datetime.datetime.strptime(s, "%d/%m/%Y").timetuple()))
df_ratings.loc[mask]

         userId  movieId  rating   timestamp
3534         31        1     3.0  1424733487
3535         31      110     5.0  1424733473
3536         31      260     5.0  1424733433
3537         31      364     3.0  1424844807
3538         31      527     0.5  1424733598
3539         31      588     3.0  1424842869
3540         31      594     2.5  1424844811
3541         31      616     4.0  1424844817
3542         31     1196     5.0  1424733435
3543         31     1197     3.0  1424734492
3544         31     1207     0.5  1424734478
3545         31     1210     5.0  1424733439
3546         31     1214     0.5  1424733574
3547         31     1270     4.0  1424733467
3548         31     2096     2.0  1424844830
3549         31     2571     4.5  1424736532
3550         31     2959     2.0  1424734458
3551         31     3300     5.0  1424733940
3552         31     3483     4.0  1424735625
3553         31     3555     3.0  1424734355
3554         31     3615     3.0  1424734207
3555         31     3624     3.0  1424733917
3556         31     3671     5.0  1424733819
3557         31     3751     4.0  1424736599
3558         31     3793     4.5  1424734262
3559         31     3916     4.5  1424734610
3560         31     4016     4.0  1424733990
3561         31     4022     2.0  1424734536
3562         31     4232     4.0  1424734082
3563         31     4299     3.0  1424733987
...         ...      ...     ...         ...
1037827    7036    91653     2.0  1427729252
1037857    7036    96801     3.0  1424672553
1037900    7036   103974     4.0  1424009549
1037918    7036   106920     4.0  1426488409
1037929    7036   109487     4.0  1427729683
1037939    7036   112183     3.0  1427733485
1037944    7036   113862     2.5  1427729287
1037945    7036   114060     3.0  1424788575
1037946    7036   115149     2.5  1424164039
1037947    7036   115569     4.5  1426428943
1037950    7036   117176     4.5  1424687339
1037951    7036   120635     2.5  1425296056
1037952    7036   128356     1.5  1423563309
1037953    7036   128358     3.0  1423563422
1042722    7064     4973     3.0  1425396199
1042789    7064    40148     3.0  1427299673
1042807    7064    48738     3.0  1425395718
1042868    7064    86911     3.5  1427196633
1042871    7064    88744     4.0  1426502560
1042880    7064    93510     3.5  1427196607
1042881    7064    95441     3.5  1427196652
1042883    7064    96079     3.5  1426502623
1042887    7064    98809     4.5  1425396754
1042892    7064   104879     3.5  1427199365
1042898    7064   109487     4.5  1427121449
1042907    7064   116797     3.5  1426502587
1043278    7066     1348     3.0  1424574945
1043337    7066    97957     5.0  1426390944
1043340    7066   102802     3.0  1427075294
1043343    7066   106868     4.0  1426384822

[8849 rows x 4 columns]

**XV. Sort the tags DataFrame based on timestamp.**

In [52]:
#df_tags.head()
df_tags.sort_values(['timestamp'], ascending=[True])

        userId  movieId                              tag   timestamp
333932  100371     2788                     monty python  1135429210
333927  100371     1732                    coen brothers  1135429236
333924  100371     1206                  stanley kubrick  1135429248
333923  100371     1193                   jack nicholson  1135429371
333939  100371     5004                    peter sellers  1135429399
333922  100371       47                   morgan freeman  1135429412
333921  100371       47                        brad pitt  1135429412
333936  100371     4011                        brad pitt  1135429431
333937  100371     4011                      guy ritchie  1135429431
333920  100371       32                     bruce willis  1135429442
333933  100371     2858                     kevin spacey  1135429466
333931  100371     2329                     fuckoff nazi  1135429508
333930  100371     2329                    edward norton  1135429508
333944  100371     6016                           brazil  1135429520
15903     3797      110                        overrated  1135589075
256663   75141     4642                         Terrible  1135688095
15926     3797     8573             Nonlinear Surrealism  1135936223
68928    16050    38886                             twee  1136036612
68924    16050    38886                         eighties  1136036612
68925    16050    38886                           family  1136036612
68926    16050    38886                         new york  1136036612
68927    16050    38886                        overrated  1136036612
68919    16050     7060                        christian  1136039301
68921    16050     7060                          musical  1136039301
68920    16050     7060                           kitsch  1136039301
68922    16050     7060                        religious  1136039301
68918    16050     6898                            harsh  1136039368
68916    16050     6898                          british  1136039368
68917    16050     6898                            drugs  1136039368
81444    20513    36529                            truth  1136242623
...        ...      ...                              ...         ...
119997   28906   115149                          violent  1427746031
119991   28906   115149                    lack of story  1427746053
119993   28906   115149                     over the top  1427746060
119989   28906   115149                           cheesy  1427746074
405155  123297   128642                              CLV  1427746337
399877  123297     4211                              CLV  1427746709
400993  123297     6419                              CLV  1427746864
401017  123297     6481                              CLV  1427747220
405123  123297   118722                              CLV  1427747321
400106  123297     4573                              CLV  1427747462
150873   42640   115122                     mockumentary  1427748778
150871   42640   115122                           comedy  1427748797
150872   42640   115122                      dark comedy  1427748808
392905  122523     5004                              USA  1427752289
392904  122523     5004                            party  1427752292
290536   88044   106782              unsatisfying ending  1427753000
290534   88044   106782                           Orgies  1427753111
290529   88044   106782                             ENFP  1427753147
290532   88044   106782             Left-Wing Propaganda  1427753266
290533   88044   106782                Left-Wing Writers  1427753621
290528   88044   106782  Economically Illiterate Writers  1427753739
290530   88044   106782                       inaccurate  1427753806
290531   88044   106782                       Jonah Hill  1427753849
290526   88044   106782                           Amoral  1427753913
290527   88044   106782                            crime  1427753921
290535   88044   106782                        profanity  1427754096
288375   87797      215                           Vienna  1427755801
158763   46072     3409                      premonition  1427760726
158780   46072     6058                      premonition  1427760764
339178  102853   115149                    russian mafia  1427771352

[465564 rows x 4 columns]